######################################################################
# FILTERS FOR INTERNAL FILES
#
# REVISION HISTORY
# 01.00  2015-08-12  visbwa  Initial creation (based on BrsAsr3 version)
######################################################################

#TGF FILES
FILTER_TGF_COMASRVERSIONABSTRACTION += $(FILTER_INTERNAL)
FILTER_TSIDIAG_ASRDCM += $(FILTER_INTERNAL)
FILTER_TSIDIAG_ASRDCMAPPL += $(FILTER_INTERNAL)
FILTER_TSIIL_ASRCOM += $(FILTER_INTERNAL)
FILTER_TSIIL_ASRCOMGEN += $(FILTER_INTERNAL)
FILTER_TSIMODEMGT += $(FILTER_INTERNAL)
FILTER_TSINVM += $(FILTER_INTERNAL)
FILTER_TSINVM_CFG += $(FILTER_INTERNAL)
FILTER_TSINVM_FUNCTIONSET += $(FILTER_INTERNAL)
FILTER_TSITESTGENERATORFRAMEWORK += $(FILTER_INTERNAL)
FILTER_TSITESTGENERATORFRAMEWORKAPPL += $(FILTER_INTERNAL)
FILTER_TSITGFGENERICCALLBACK += $(FILTER_INTERNAL)
FILTER_TSIXCP += $(FILTER_INTERNAL)


#BRS FILES
FILTER_BRSASRAPPL += $(FILTER_INTERNAL)
FILTER_BRSASRINIT += $(FILTER_INTERNAL)
FILTER_BRSASRMAIN += $(FILTER_INTERNAL)
FILTER_ZOS_EMU += $(FILTER_INTERNAL)
FILTER_ZOS_EMU_ERR += $(FILTER_INTERNAL)
FILTER_BRSHW += $(FILTER_INTERNAL)
FILTER_BRSINTTB += $(FILTER_INTERNAL)


#######################################################################
# ADDITIONAL CFLAGS FOR INTERNAL FILES
#######################################################################

#TGF FILES
CFLAGS_TGF_COMASRVERSIONABSTRACTION += $(CFLAGS_INTERNAL)
CFLAGS_TSIDIAG_ASRDCM += $(CFLAGS_INTERNAL)
CFLAGS_TSIDIAG_ASRDCMAPPL += $(CFLAGS_INTERNAL)
CFLAGS_TSIIL_ASRCOM += $(CFLAGS_INTERNAL)
CFLAGS_TSIIL_ASRCOMGEN += $(CFLAGS_INTERNAL)
CFLAGS_TSIMODEMGT += $(CFLAGS_INTERNAL)
CFLAGS_TSINVM += $(CFLAGS_INTERNAL)
CFLAGS_TSINVM_CFG += $(CFLAGS_INTERNAL)
CFLAGS_TSINVM_FUNCTIONSET += $(CFLAGS_INTERNAL)
CFLAGS_TSITESTGENERATORFRAMEWORK += $(CFLAGS_INTERNAL)
CFLAGS_TSITESTGENERATORFRAMEWORKAPPL += $(CFLAGS_INTERNAL)
CFLAGS_TSITGFGENERICCALLBACK += $(CFLAGS_INTERNAL)
CFLAGS_TSIXCP += $(CFLAGS_INTERNAL)


#BRS FILES
CFLAGS_BRSASRAPPL += $(CFLAGS_INTERNAL)
CFLAGS_BRSASRINIT += $(CFLAGS_INTERNAL)
CFLAGS_BRSASRMAIN += $(CFLAGS_INTERNAL)
CFLAGS_ZOS_EMU += $(CFLAGS_INTERNAL)
CFLAGS_ZOS_EMU_ERR += $(CFLAGS_INTERNAL)
CFLAGS_BRSHW += $(CFLAGS_INTERNAL)
CFLAGS_BRSINTTB += $(CFLAGS_INTERNAL)

